### ISSUE TITLE
Going after a refactor of the emulator selection

### ISSUE THREAD

**Issue by Mirv** [woody34/L2RBot#11]
Not going to work on this one actually, not sure about ToS stuff with their app.

**Comment by woody34** [comment]
Hello @Mirv, Thank you for your interest in my project! I would be happy to collaborate with you. I have been using this project as an effort to learn more about programming myself. I come from more of a hobby scripting background, AutoIT to be specific. The UI is a mess and I do need to work it out. I really just threw it together to get it working. Feel free to refactor as much as you like! Let me know if I can help in any way. My discord is Woody #7943 if you would like to chat.
