### ISSUE TITLE
i need L2RBot_TemporaryKey.pfx to compile?

### ISSUE THREAD

**Issue by mmhinz** [woody34/L2RBot#13]
hi, morning

i need L2RBot_TemporaryKey.pfx to compile? 

thx

**Comment by woody34** [comment]
Hello @mmhinz, from what I understand, you can disable this by going to the projects properties>Signing and unchecking the checkbox labeled 'Sign the ClickOnce manifests'.

![image](https://user-images.githubusercontent.com/8930703/35421810-d620ac16-020a-11e8-80a7-387b2c84aa33.png)

I never set any passwords on anything related to this project. Also you might comment out the requestedExecutionLevel element of the app.manifest file and test it to see if it meets your needs. If I recall correctly I had to add that to let me resize BlueStacks window to 1280x720. Let me know if this resolves your issue or if I can help in any other way.
