### ISSUE TITLE
Heya need some help!

### ISSUE THREAD

**Issue by pcenthusiast92** [woody34/L2RBot#14]
Hello mr Woody34 i was wondering how can i use your bot? for L2R? i already downloaded the L2bot-master.zip but im totally lost hehe, i'm using nox, thanks.

**Comment by woody34** [comment]
https://github.com/woody34/L2RBot/issues/15 - will help you get the project working in VS

https://github.com/woody34/L2RBot/issues/12 - will give you a basic idea how to add a feature
