### ISSUE TITLE
Some tips required

### ISSUE THREAD

**Issue by adeleglise** [woody34/L2RBot#15]
Hey, since a lot of the UI has changed, I wanted to try my hands at updating this.

I've cloned the repo and opened the projet in Visual Studio. I've also clone the NHotkey repo, as it seems to be a dependency.

However, when I try to build it, there's issues regarding the certificate, and the CPU type of ADB.

Could you help with this ?

**Comment by woody34** [comment]
Post the specific errors you're getting and I will help out. I have actually deleted the main project from my dev box so I will have to clone it myself. I should have some time later this evening. Thanks.

**Comment by woody34** [comment]
Sorry for the delay. I cloned the project, opened the solution, installed the Nuget libraries for NHotkey.WPF and log4net and it fired right up. If you are getting a certificate error you may look at this previously reported issue. 

https://github.com/woody34/L2RBot/issues/13

When you get a chance to post the specific errors you are getting I will address them more thouroughly. Thanks.

**Comment by adeleglise** [comment]
Hey, thanks for this answer.

I close this issue for now and get back to you when I have some time to look more in depth.
