### ISSUE TITLE
help with the bot

### ISSUE THREAD

**Issue by kardinal56** [woody34/L2RBot#16]
Hello,
i am kinda lost on the bot.exe thing, i cant finde it anywhere, i dont now where to look.
If anyone can post me a guide video or help me out i would much appreciate.

Thanks

**Comment by woody34** [comment]
You can download the latest exe in the releases section of github. This project hasn't been supported for months. I haven't tested the bot but I would venture to guess that it needs to have the pixel values updated to be funtional. Any minor UI change in the game requires that the pixel values be updated. 

https://github.com/woody34/L2RBot/releases
