### ISSUE TITLE
Can not run L2R windows 10

### ISSUE THREAD

**Issue by braverynew** [woody34/L2RBot#2]
Pls help me to run it on windows 10. The app always minimize.

**Comment by woody34** [comment]
At which point does it minimize? What resolution do you have windows set to?

**Comment by braverynew** [comment]
My windows resolution is 1920x1080. The app L2R always in taskbar

**Comment by woody34** [comment]
NoxPlayer will show an icon in the task bar but usually the bot will initialize to pixel location 1300,0. Once you start the bot it will move all NoxPlayer instances to 0,0. do you run multi monitors? can you show me a screen cap of your problem?

You should see this after opening the executable. Are you running it through visual studio or using the .exe binary I provided?
![screenshot 519](https://user-images.githubusercontent.com/8930703/31916168-fac6c11a-b816-11e7-9af6-1d4e0872ccb2.png)
