### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Laezor** [woody34/L2RBot#3]
im using noxplayer as you said. Set resolution to 1280x720. i get error my screen is 1254x732 something like that any help?

**Comment by woody34** [comment]
Send me a screencap of your window and which version of Nox you are using. Depending on which version of Nox Player you're using you may need to change some of the border settings. They changed the border sizes around version 5.0.0. Also you may have accedentally dragged the window and resized it. You can fix that by changing the window in Nox to a different size and then back to 1280x720.
