### ISSUE TITLE
L2Rbot request

### ISSUE THREAD

**Issue by grosbok** [woody34/L2RBot#5]
I know your bot is in the early builds but i was wondering once everything is working smooth if you could add a portion to the bot to upgrade armors and open boxes?

So far i like the fast reponse the bot has.

Keep up the good work.

**Comment by woody34** [comment]
Thanks, I can add those items to my list of features. What specifically would you like to see? Upgrade gear equiped to your character? upgrade A's in your inventory? The logic for those features would be rather complex. As for opening boxes, which boxes are you refering to? I had a  bulk sale feature working on an early build for SEA. I could bring that back if interested?

**Comment by grosbok** [comment]
Bulk sale would be great to help clean up inventory when questing. Has for upgrade maybe it's not worth it if you add you bulk sale option. Has for the opening boxes, i'm talking about the reward we get from dailies/questing.

**Comment by woody34** [comment]
Ok. I will add the features that I am working on. As for your issue with Nox, I could probably add an option to disable the toggling of the screens for single bot instances. I would also have to add support for chosing which Nox processes you would like the bot active on. Those are both things I planned on working on in the future so I will see what I can do!

**Comment by grosbok** [comment]
Ok thanks for you time and effort on this.

**Comment by woody34** [comment]
My most recent release addresses a couple of the issues you were having. I added options to let the user chose if they would like the windows homed to Point(0,0), You can now turn off window cycling so you can bot on one screen and play on another(kind of.) and you can now also chose which Nox windows you would like to run the bot on. After you hit Find Nox you can select the windows you would like the bot to ignore. Until I can find a method to send virtual mouse clicks to nox player the mouse will still have to move to click the screen on your second box. I will se what I can do about that in the future.
