### ISSUE TITLE
doesn't work on my end when resizing window

### ISSUE THREAD

**Issue by bovas85** [woody34/L2RBot#9]
I have set 1280x720 but my nox player won't change size. How do I know what the correct size is?

Also any way to reduce the interval so I can actually stop the program?

**Comment by woody34** [comment]
To stop the bot you can press Ctrl + Alt + S. If you would like sleep intervals you could add a sleep timer to the quest method in MainWindow.xaml.cs. for example you could make the WeeklyBot() look like this.

```C#
if(bots[ind].Complete == false)
{
     bots[ind].Start();
     Thread.Sleep(5000);//This will create a 5 second interval.
}
```

as for your screen size, it will have to remain 1280x720 for the pixel bot to detect the correct pixels. If you have dragged the NoxPlayer window out of size you will have to go to NoxPlayer settings. 

1. -change the resolution to 1920x1080, hit save, don't worry about doing a restart, 
2. -change the resolution to 1280x720, hit save and restart. 

This will get you back to a true 1280x720.

**Comment by bovas85** [comment]
Hey @woody34 thanks for that. I managed to stop the error in the log. But it won't work. It only clicks the first time but won't accept quests. Is the bot compatible with the last version or where should I look to fix that?

**Comment by bovas85** [comment]
Hey @woody34 thanks for that. I managed to stop the error in the log. But it won't work. It only clicks the first time but won't accept quests. Is the bot compatible with the last version or where should I look to fix that?

**Comment by bovas85** [comment]
Any idea?

**Comment by woody34** [comment]
Make sure you have this version https://github.com/woody34/L2RBot/releases/tag/v0.1.04-Beta 
this version is compatible with the Main, Weekly, and Scroll quests on the latest version of L2R 1.06. I run it with Nox Player v5 on one PC and v6 on another, both on Windows 10. Both of my boxes are Intel CPU's with Nvidia GPU's. If you can create a nox screenshot and link it I may be able to offer you more help. Also I would like to know more about your computer specs.

**Comment by bovas85** [comment]
Thanks will try that version and come back to you

**Comment by Jeapordy** [comment]
One thing I noticed is that the top window border for nox version 6.0.0.0 (45px) and 6.0.1.0 (30px) differ.  In looking at the code I am betting Nox 5.x must have used 30px.  If you are still having issues, and are using Nox 6.0.0.0 try upgrading to 6.0.1.0 and see if it works better.

**Comment by woody34** [comment]
Thanks for the heads up @Jeapordy, I haven't upgraded to 6.0.1.0 yet. I'm still running 6.0.0.0. I will upgrade soon and correct for any changes.

I am currently working on adding ADB support so that my bot will be able to directly interace Android OS inside of Nox. This will fix a lot of the issues/compaints people have with my bot. 


- Windows screen size will no longer be an issue. 
- Your computer won't be tied up while botting. It can just run in the background, minimized even.

I have it working now, I'm debugging it now, I should be done afternoon. Keep an eye out for the next release!

**Comment by bovas85** [comment]
Fantastic news woody

**Comment by woody34** [comment]
https://github.com/woody34/L2RBot/releases/tag/v0.1.06-Beta

This version supports ADB. (Settings>General>Emulator>ADb) It requries you turn on USB debugging and enable root access. This should resolve the window resizing issue you where having. Let me know if you have any problems.

**Comment by bovas85** [comment]
It works great with that, the only issue is the advert popups when opening the inventory, which block the bot into the inventory page.

**Comment by bovas85** [comment]
getting a scroll quest crash every time I try to start them:
```
Application: L2RBot.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at L2RBot.Scroll.ComparePref()
   at L2RBot.Scroll.FindScroll()
   at L2RBot.Scroll.Start()
   at L2RBot.MainWindow.ScrollBot()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by woody34** [comment]
Yeah, I broke a couple of things when I added ADB support. I fixed them in the latest release. https://github.com/woody34/L2RBot/releases 

Try that one and let me know if you get the same error. I have been using it with no issues. I will add the new popups to QuestHelper soon, as well.

**Comment by bovas85** [comment]
Thanks it won't crash anymore. It only does one scroll quest though. It only opens up the scroll selection on the second one, then it stops.
